name: ngtools
channels:
  - conda-forge
dependencies:
  - python
  - numpy>=1.20
  - dask
  - fsspec>=2021.0.0
  - cryptography>=36.0.2
  - universal_pathlib
  - nibabel
  - nitransforms>=22.0
  - tifffile
  - zarr
  - indexed_gzip
  - dandi>=0.44
  - requests
  - pip
  - pip:
    - fsspec[full]
    - neuroglancer
    - cloud-volume