name: Publish ngtools-pyscript on PyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Commit / Branch / Tag / SHA to checkout'
        required: false
        default: 'main'
      publish:
        description: 'Publish'
        required: false
        default: 'test+pypi'
        type: choice
        options:
          - 'pypi'
          - 'test'
          - 'test+pypi'
      python-version:
        description: 'Python version'
        required: false
        default: '3.11'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies for building package
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build
        shell: bash
      - name: Build a binary wheel and a source tarball
        run: |
          cd ngtools-pyscript
          python -m build
        shell: bash
      - name: Publish distribution 📦 to Test PyPI
        if: ${{ contains(inputs.publish, 'test') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: ${{ contains(inputs.publish, 'pypi') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
